### ISSUE TITLE
Parsing multiple hosts

### ISSUE THREAD

**Issue by rolfr0fl** [AresS31/testssl2xlsx#1]
Hi AresS31,

first of all thank you very much for you effort and this script. I'm just wondering if there is a way to parse multiple hosts/json files. Maybe I overlooked something but with testssl I can scan one host at a time (or using the -file option, but then multiple json files are created). Therefore, is there any possibility right now to create an Excel sheet with multiple hosts?

Thank you very much!

Regards
rolf

**Comment by aress31** [comment]
Hi @rolfr0fl 

Please see the following command to generate **only** a single `JSON` output file when using `testssl`:
`testssl.sh --jsonfile-pretty testssl-results.json --quiet --nodns --parallel --server-defaults --protocols --vulnerable --file ../nmap/full_SYN.gnmap`

_Note: The `--jsonfile-pretty` is the switch responsible for the generation of only one `JSON` output._

Kind regards,
Alex
