### ISSUE TITLE
Parsing error: Expecting property name

### ISSUE THREAD

**Issue by l4rm4nd** [AresS31/testssl2xlsx#2]
I've scanned some host with testssl and the resulting json file causes a parsing error.
Line 291 has a missing "finding" property, which results into the error.

Here is the testssl.sh json file (extension renamed to log; IP changed):
[example_testssl_file.log](https://github.com/AresS31/testssl2xlsx/files/1841382/example_testssl_file.log)

Best regards

**Comment by l4rm4nd** [comment]
Guess it's a testssl.sh bug, where the "banner_server" id has no "finding" property, but the script nonetheless appends the "," delimiter. Other ids however always contain `"finding" : "--"`.

@drwetter

**Comment by drwetter** [comment]
Not sure why that happened. There was a bug when the server side supplied a blank. Please update and try.

Otherwise I would need a real IP. And an issue filed upstream would be great.
